### PR TITLE
week1-0830

### PR DESCRIPTION
**Pull request by lark1987**
彭彭老師好 ~ 我是賴亭如 ~ 來交第一週的作業 ~

http://15.168.102.124:3000/api/attractions?page=1&keyword=劍潭
http://15.168.102.124:3000/api/attractions/10
http://15.168.102.124:3000/api/mrts

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
We should handle endpoints like this http://15.168.102.124:3000/api/attractions?page=0 where keyword is optional parameter and page should started from 0.

Re-request review after you fixed this issue.

**Comment by lark1987** [comment]
彭彭老師好 ~ 補上修正版 ~

**Comment by cwpeng** [comment]
MySQL connection is lost due to long time (more than 8 hours for default) inactivity. Try to use connection pool or set longer timeout interval in your MySQL server.

**Comment by lark1987** [comment]
彭彭老師好 ~ 補上修正版 ~

**Review by cwpeng — CHANGES_REQUESTED** [review]
You get a connection from connection pool at server started and re-use it without closing. It just works like there is no connection pool.

Try to:
1. Create connection pool at server started.
2. When you handle request, get a connection from pool and close it after using.

Contact me at Discord if any further question.

**Comment by lark1987** [comment]
原來是這樣 ! 有修正連線的方式 ~ 再請老師看看 ~

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
