### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by lark1987**
彭彭老師好 ~ 我是賴亭如 ~ 來繳交本週任務 ~
http://15.168.102.124:3000/
http://15.168.102.124:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Basic font size for most text in your homepage and attraction page is too large.
2. Second separating line should be only 1px height.
3. Image slider in mobile devices should be extending to full width and keep no space with navigator bar.
4. Layout in mobile device should align in center.

**Comment by lark1987** [comment]
彭彭老師好 ~ 有進行修改 ~ 再請您檢核 ~

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Basic font size should align with design.
2. Second separating line should be only 1px height.

**Comment by lark1987** [comment]
有再行修正 ~ 再請老師幫忙確認 ~

**Comment by lark1987** [comment]
追加修正 ~

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
